version: 1.5.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: wallabag.Api.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 2iwVxq464+maZ/gjLOqn0mvgYfELP0Q/R4drYUpRCeEZfKRnfFEod9il43nqRjtn
  on:
    branch: master