version: 1.5.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu1804
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: wallabag.Api.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 2iwVxq464+maZ/gjLOqn0mvgYfELP0Q/R4drYUpRCeEZfKRnfFEod9il43nqRjtn
  on:
    branch: master